name: vehiloc
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  riverpod: ^2.4.9
  provider: ^6.1.1
  logger: ^2.0.2+1
  intl: ^0.19.0
  connectivity_plus: ^5.0.2
  label_marker: ^1.0.1
  flutter_riverpod: ^2.4.9
  shared_preferences: ^2.2.2
  flutter_hooks: ^0.20.4
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0
  hexcolor: ^3.0.1
  google_maps_flutter: ^2.5.3
  build_runner: ^2.4.8
  http: ^1.2.0
  flutter_slidable: ^3.0.1
  dio: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
  - assets/logo/vehiloc-logo-splash.png # asset logo to launch splash 
  - assets/icons/
  - assets/icons/navigate.png
  - assets/icons/navigate-red.png
  - assets/icons/navigate-green.png

