name: VehiLoc
description: "Cara mudah tracking kemana saja armada Anda pergi."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.4.9
  intl: ^0.19.0
  connectivity_plus: ^5.0.2
  label_marker: ^1.0.1
  shared_preferences: ^2.2.2
  flutter_hooks: ^0.20.4
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0
  hexcolor: ^3.0.1
  google_maps_flutter: ^2.5.3
  build_runner: ^2.4.8
  http: ^1.2.0
  flutter_slidable: ^0.6.0
  dio: ^5.4.0
  infinite_scroll_pagination: ^4.0.0
  label_google_maps_marker: ^0.0.3
  flutter_native_splash: ^2.3.2
  syncfusion_flutter_charts: ^24.2.3+1
  pdf: ^3.10.7
  image_gallery_saver: ^2.0.3

flutter_native_splash:
  android: true
  ios: true
  color: "#7D0A0A"
  image: assets/logo/vehiloc-logo.png
  android_12:
    color: "#7D0A0A"
    image: assets/logo/vehiloc-logo.png

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  logger: ^2.0.2+1

flutter:
  uses-material-design: true

  assets:
    - assets/logo/vehiloc-logo.png
    - assets/icons/
    - assets/icons/navigate.png
    - assets/icons/navigate-red.png
    - assets/icons/navigate-green.png
    - assets/icons/arrow_green.png
    - assets/icons/arrow_red.png
    - assets/icons/arrow_gray.png
